export const ROUTES = {
  home: '/',
  aboutUs: '/about-us',
  contacts: '/contacts',
  guarantee: '/guarantee',
  delivery: '/delivery',
  news: '/news',
  feedback: '/feedback',
  tires: '/tires',
  tire: '/tires/:id',
  wheels: '/wheels',
  wheel: '/wheels/:id',
  wheelSpacers: '/wheel-spacers',
  wheelSpacer: '/wheel-spacers/:id',
  searchEmpty: '/products/title',
  search: '/products/title/:title',
  profile: '/profile',
  favorites: '/favorites',
  cart: '/cart',
  returnExchange: '/returnExchange',
  payment: 'payment',
} as const;
